services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    labels:
      - swag=enable
      - swag_address=${SWAG_ADDRESS}
      - swag_port=9200
      - swag_url=opensearchnode.*
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}

    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - shared-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    labels:
      - swag=enable
      - swag_address=${SWAG_ADDRESS}
      - swag_port=5601
      - swag_url=opensearch.*
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS}
    networks:
      - shared-net
    depends_on:
      - opensearch-node

volumes:
  opensearch-data:

networks:
  shared-net:
    external: true
    name: shared-net
