services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      WATCHTOWER_SCHEDULE: 0 0 9 * * FRI
      WATCHTOWER_NOTIFICATIONS: email 
    env_file:
      - ./.env
