services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1002
      - URL=${DOMAIN_NAME}
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-docker|linuxserver/mods:universal-cloudflared
      - DOCKER_HOST=dockerproxy
      - FILE__CF_TUNNEL_CONFIG=/config/tunnelconfig.yml
      - PROPAGATION=60
      - TZ=America/Chicago
      - CERTPROVIDER=zerossl
      - EMAIL=${EMAIL}
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
      - MAXMINDDB_USER_ID=${MAXMINDDB_USER_ID}
    env_file:
      - ./.env
    extra_hosts:
      - ${DOMAIN_NAME}:127.0.0.1
    ports:
      - 81:81
    restart: unless-stopped
    networks:
      - shared-net
    volumes:
    - ./config:/config
    - /etc/localtime:/etc/localtime:ro
    - ../vaultwarden/logs:/shared-logs/vaultwarden:ro
    - ../nextcloud/data/nextcloud.log:/shared-logs/nextcloud/nextcloud.log:ro
    - ../homeassistant/ha/config/home-assistant.log:/shared-logs/homeassistant/home-assistant.log

  dockerproxy:
    image: lscr.io/linuxserver/socket-proxy
    container_name: dockerproxy
    networks:
      - shared-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - POST=0
    restart: unless-stopped

networks:
  shared-net:
    driver: bridge
    name: shared-net
    ipam:
      config:
        - subnet: ${SUBNET}
